name: Package version bump
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Test for changed files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            src/
            package.json
            tsconfig.json
            README.md
            yarn.lock

      - name: Check if package.json version has been modified
        shell: bash
        if: ${{ github.base_ref == 'main' && steps.changed-files.outputs.any_changed == 'true' }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          if PAGER= git diff --unified=0 origin/main package.json | grep version > /dev/null; then
            echo "Looking good!";
          else
            echo "Please bump package.json as the following files have changed";
            echo "$ALL_CHANGED_FILES";
            exit 1;
          fi
