name: Package version bump
on:
  pull_request:

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Test for changed files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            src/
            package.json
            tsconfig.json
            README.md
            yarn.lock

      - name: Break if package.json was not changed
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          maybe_bumped=false ;
          for file in ${ALL_CHANGED_FILES}; do
            if [[ "$file" == *"package.json" ]]; then
              echo "$file was bumped" ;
              maybe_bumped=true ;
            fi
          done

          if [[ "$maybe_bumped" == "false" ]]; then
            echo "Please bump package.json as the following files have changed";
            echo "$ALL_CHANGED_FILES";
            exit 1;
          fi
